import { User, Campaign, Account } from "@/types";

export const users: User[] = [
  { id: "USR001", name: "Alice Johnson", email: "alice@example.com", role: "client", avatar: "/avatars/01.png", status: "active", adAccountIds: ["act_1111", "act_5555"] },
  { id: "USR002", name: "Bob Williams", email: "bob@example.com", role: "client", avatar: "/avatars/02.png", status: "active", adAccountIds: ["act_2222"] },
  { id: "USR003", name: "Charlie Brown", email: "charlie@example.com", role: "client", avatar: "/avatars/03.png", status: "archived", adAccountIds: ["act_3333"] },
  { id: "USR004", name: "Diana Prince", email: "diana@example.com", role: "client", avatar: "/avatars/04.png", status: "active", adAccountIds: ["act_4444"] },
];

export const accounts: Account[] = [
  {
    id: "act_1111",
    name: "Alice Johnson's Account",
    accessToken: "ALICE_FAKE_TOKEN",
    clientName: "Alice Johnson",
    companyName: "Alice's Awesome Widgets",
    campaigns: [
      {
        id: "CAM001",
        name: "Summer Sale 2024",
        status: "active",
        reach: 120540,
        impressions: 550345,
        conversions: 2450,
        ctr: 2.5,
        cpc: 0.75,
        cpm: 3.50,
        platform: "Facebook",
        linked: true,
        client: "Alice Johnson",
        description: "A campaign to promote our summer collection with discounts up to 50%.",
      },
      {
        id: "CAM005",
        name: "Low Performer Example",
        status: "active",
        reach: 1500,
        impressions: 5000,
        conversions: 10,
        ctr: 0.5,
        cpc: 3.00,
        cpm: 8.00,
        platform: "Facebook",
        linked: true,
        client: "Alice Johnson",
        description: "This is a sample low-performing campaign.",
      },
       {
        id: "CAM007",
        name: "SR_WEDDING",
        status: "active",
        reach: 718870,
        impressions: 171561,
        conversions: 191,
        ctr: 0.53,
        cpc: 10.51,
        cpm: 8.75,
        platform: "Facebook",
        linked: true,
        client: "Alice Johnson",
        description: "Wedding services promotion campaign.",
      },
      {
        id: "CAM008",
        name: "SR_WEDDING",
        status: "active",
        reach: 9136,
        impressions: 10291,
        conversions: 60,
        ctr: 1.66,
        cpc: 32.93,
        cpm: 34.31,
        platform: "Facebook",
        linked: true,
        client: "Alice Johnson",
        description: "Wedding services promotion campaign.",
      },
      {
        id: "CAM009",
        name: "SR_WEDDING",
        status: "active",
        reach: 179781,
        impressions: 395925,
        conversions: 331,
        ctr: 0.14,
        cpc: 10.45,
        cpm: 3.65,
        platform: "Facebook",
        linked: true,
        client: "Alice Johnson",
        description: "Wedding services promotion campaign.",
      }
    ]
  },
  {
    id: "act_5555",
    name: "Alice Johnson's Second Account",
    accessToken: "ALICE_FAKE_TOKEN_2",
    clientName: "Alice Johnson",
    companyName: "Alice's Garden Supplies",
    campaigns: [
       {
        id: "CAM006",
        name: "Spring Planting Sale",
        status: "active",
        reach: 85000,
        impressions: 320000,
        conversions: 1500,
        ctr: 3.1,
        cpc: 0.90,
        cpm: 4.10,
        platform: "Instagram",
        linked: true,
        client: "Alice Johnson",
        description: "Sale on all spring gardening essentials.",
      },
    ]
  },
  {
    id: "act_2222",
    name: "Bob Williams' Account",
    accessToken: "BOB_FAKE_TOKEN",
    clientName: "Bob Williams",
    companyName: "Bob's Burger Bar",
    campaigns: [
       {
        id: "CAM002",
        name: "New Product Launch",
        status: "paused",
        reach: 56780,
        impressions: 210890,
        conversions: 890,
        ctr: 1.8,
        cpc: 1.20,
        cpm: 5.20,
        platform: "Instagram",
        linked: true,
        client: "Bob Williams",
        description: "Launching the new X-series gadget.",
      },
    ]
  },
  {
    id: "act_3333",
    name: "Charlie Brown's Account",
    accessToken: "CHARLIE_FAKE_TOKEN",
    clientName: "Charlie Brown",
    companyName: "Charlie's Cybernetics",
    campaigns: [
      {
        id: "CAM003",
        name: "Brand Awareness Q3",
        status: "active",
        reach: 350000,
        impressions: 1200000,
        conversions: 120,
        ctr: 0.8,
        cpc: 0.25,
        cpm: 1.50,
        platform: "Facebook",
        linked: false,
        client: "Charlie Brown",
        description: "General brand awareness campaign.",
      },
    ]
  },
  {
    id: "act_4444",
    name: "Diana Prince's Account",
    accessToken: "DIANA_FAKE_TOKEN",
    clientName: "Diana Prince",
    companyName: "Diana's Dazzlers",
    campaigns: [
        {
        id: "CAM004",
        name: "Holiday Giveaway",
        status: "archived",
        reach: 95000,
        impressions: 450000,
        conversions: 5600,
        ctr: 4.2,
        cpc: 0.50,
        cpm: 2.80,
        platform: "Instagram",
        linked: true,
        client: "Diana Prince",
        description: "A giveaway contest to boost engagement.",
      },
    ]
  }
];

// This export can be deprecated or used for the admin view to show all campaigns at once.
export const campaigns: Campaign[] = accounts.flatMap(acc => acc.campaigns);
