import { User, Campaign } from "@/types";

export const users: User[] = [
  { id: "USR001", name: "Alice Johnson", email: "alice@example.com", role: "client", avatar: "/avatars/01.png", status: "active" },
  { id: "USR002", name: "Bob Williams", email: "bob@example.com", role: "client", avatar: "/avatars/02.png", status: "active" },
  { id: "USR003", name: "Charlie Brown", email: "charlie@example.com", role: "client", avatar: "/avatars/03.png", status: "archived" },
  { id: "USR004", name: "Diana Prince", email: "diana@example.com", role: "client", avatar: "/avatars/04.png", status: "active" },
];

export const campaigns: Campaign[] = [
  {
    id: "CAM001",
    name: "Summer Sale 2024",
    status: "active",
    reach: 120540,
    impressions: 550345,
    conversions: 2450,
    ctr: 2.5,
    cpc: 0.75,
    cpm: 3.50,
    platform: "Facebook",
    linked: true,
    client: "Alice Johnson",
    description: "A campaign to promote our summer collection with discounts up to 50%. Targeted at young adults aged 18-30.",
  },
  {
    id: "CAM002",
    name: "New Product Launch",
    status: "paused",
    reach: 56780,
    impressions: 210890,
    conversions: 890,
    ctr: 1.8,
    cpc: 1.20,
    cpm: 5.20,
    platform: "Instagram",
    linked: true,
    client: "Bob Williams",
    description: "Launching the new X-series gadget. Focus on tech enthusiasts and early adopters.",
  },
  {
    id: "CAM003",
    name: "Brand Awareness Q3",
    status: "active",
    reach: 350000,
    impressions: 1200000,
    conversions: 120,
    ctr: 0.8,
    cpc: 0.25,
    cpm: 1.50,
    platform: "Facebook",
    linked: false,
    client: "Charlie Brown",
    description: "General brand awareness campaign to increase our market presence. Broad targeting.",
  },
  {
    id: "CAM004",
    name: "Holiday Giveaway",
    status: "archived",
    reach: 95000,
    impressions: 450000,
    conversions: 5600,
    ctr: 4.2,
    cpc: 0.50,
    cpm: 2.80,
    platform: "Instagram",
    linked: true,
    client: "Diana Prince",
    description: "A giveaway contest to boost engagement during the holiday season. Very successful.",
  },
  {
    id: "CAM005",
    name: "Low Performer Example",
    status: "active",
    reach: 1500,
    impressions: 5000,
    conversions: 10,
    ctr: 0.5,
    cpc: 3.00,
    cpm: 8.00,
    platform: "Facebook",
    linked: true,
    client: "Alice Johnson",
    description: "This is a sample low-performing campaign designed to test the AI improvement suggestions feature. It has low reach, low CTR, and high costs.",
  }
];
